#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <random>
#include <iterator>
#include <cstring>
#include <chrono>
#include <map>
#include <cmath>
#include <typeinfo>
#include <functional>
#include <memory>
#include <thread>
#include <mutex>
#include <csignal>
#include <tuple>
#include <cstdio>	 
#include <sstream>
#include <complex>
#include <C:\Users\Nils\Downloads\boost_1_51_0\boost\algorithm\string.hpp>
#include <C:\Users\Nils\Downloads\SFML-2.4.0-windows-vc11-32-bit\SFML-2.4.0\include\SFML\Graphics.hpp>
#include <C:\Users\Nils\Downloads\SFML-2.4.0-windows-vc11-32-bit\SFML-2.4.0\include\SFML\Window.hpp>

